### ISSUE TITLE
unable to run the docker image

### ISSUE THREAD

**Issue by pvssrikanth** [luisgc93/library_api#1] opened 2021-11-21 08:30 UTC
Dear Sir,

IN UBUNTU 

(env) iibadmin@iibadmin-uat-ubuntu:~/srik/fapi/nov2021/library_api$ make env-start 
docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.python_test: 'profiles'
Makefile:2: recipe for target 'env-start' failed
make: *** [env-start] Error 1
(env) iibadmin@iibadmin-uat-ubuntu:~/srik/fapi/nov2021/library_api$ 

------------------------------------------------------------------------------------------------------------------------------------------------
I am unable to run the docker image after git clone 
CENTOS

[root@contentgateway library_api]# make env-start
docker-compose up -d
Building migration
Step 1/12 : FROM python:3.9-slim-bullseye
 ---> 3ba8c1c68e98
Step 2/12 : ENV PYTHONDONTWRITEBYTECODE 1
ERROR: Service 'migration' failed to build: error creating overlay mount to /var/lib/docker/overlay2/370bc99da935e12ee78a163deed101872475a5dd03aa468ae72be72a768876d7-init/merged: invalid argument
make: *** [env-start] Error 1
[root@contentgateway library_api]# 

AND ON UBUNTU

**Comment by luisgc93** [comment] 2022-01-23 00:38
Hi @pvssrikanth, sorry I didn't get back to you earlier. I recently updated the docker tutorial as well as the code (you'll see now that there is no migration service since we can run the alembic command directly in the dockerfile:
https://github.com/luisgc93/library_api/blob/master/Dockerfile#L21

Please try with the new version and let me know if it works.

**Comment by pvssrikanth** [comment] 2022-01-23 05:49
Dear Sir,
Thanks for your reply

However when running getting error again

(fapienv) ***@***.***:~/srik/library_api$ make start
docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.python_test: 'profiles'
Makefile:2: recipe for target 'start' failed
make: *** [start] Error 1
(fapienv) ***@***.***:~/srik/library_api$

**Comment by luisgc93** [comment] 2022-01-23 09:48
Could you check your docker-compose version?

````
➜  library_api git:(master) docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
````

**Comment by pvssrikanth** [comment] 2022-01-23 10:53
Dear Sir,

(env) ***@***.***:~/srik/library_api$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.17
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
(env) ***@***.***:~/srik/library_api$

Please guide

Thanks

**Comment by pvssrikanth** [comment] 2022-01-23 11:04
Dear Sir,
An another VM machine with high docker-compose version ALSO facing error

(env) ***@***.***:~/srik/library_api$ make start
docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.python_test: 'profiles'
Makefile:2: recipe for target 'start' failed
make: *** [start] Error 1
(env) ***@***.***:~/srik/library_api$ sudo make start
[sudo] password for iibadmin:
docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.python_test: 'profiles'
Makefile:2: recipe for target 'start' failed
make: *** [start] Error 1
(env) ***@***.***:~/srik/library_api$ docker-compose
version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
(env) ***@***.***:~/srik/library_api$

**Comment by luisgc93** [comment] 2022-01-23 11:31
You have tried with versions 1.17.1 and 1.27.4. Try with the latest version 1.29.2. I've reproduced this error with version 1.25 and fixed it when upgrading to 1.29.2

**Comment by pvssrikanth** [comment] 2022-01-23 13:32
Dear Sir
Thanks excellent support.

I was able to build (env) ***@***.***:~/srik/library_api$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED
    STATUS         PORTS                                       NAMES
e6c513142771   library_api_backend    "/bin/sh -c 'bash -c…"   9 seconds
ago   Up 7 seconds   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp
library_api_backend_1
fbde6654d765   postgres:13.3-alpine   "docker-entrypoint.s…"   2 minutes
ago   Up 9 seconds   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp
library_api_db_1
81947670f918   postgres:13-alpine     "docker-entrypoint.s…"   7 days ago
   Up 7 days      5432/tcp                                    pdfsvc_db_1
(env) ***@***.***:~/srik/library_api$ ls
alembic  alembic.ini  app  config  docker-compose.yml  Dockerfile
 heroku.yml  __init__.py  Makefile  README.md  requirements.txt  scripts
 tests
(env) ***@***.***:~/srik/library_api$

Great

Very happy to see this

**Comment by pvssrikanth** [comment] 2022-01-23 13:42
Dear Sir,
White testing from browser the API Endpoint is NOT working

(env) ***@***.***:~/srik/library_api$ vi Makefile
(env) ***@***.***:~/srik/library_api$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED
     STATUS          PORTS                                       NAMES
2b1c77166423   library_api_backend    "/bin/sh -c 'bash -c…"   34 seconds
ago   Up 32 seconds   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp
library_api_backend_1
a9a3140949cc   postgres:13.3-alpine   "docker-entrypoint.s…"   34 seconds
ago   Up 33 seconds   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp
library_api_db_1
81947670f918   postgres:13-alpine     "docker-entrypoint.s…"   7 days ago
    Up 7 days       5432/tcp                                    pdfsvc_db_1
(env) ***@***.***:~/srik/library_api$

However
[image: image.png]

**Comment by luisgc93** [comment] 2022-01-23 16:36
what endpoint?

**Comment by pvssrikanth** [comment] 2022-01-24 04:17
Hi Sir,
something is NOT running

env) ***@***.***:~/srik/library_api$ docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED
   STATUS         PORTS
NAMES
dee614ecc28e   locustio/locust        "locust -f /locust/l…"   14 hours ago
  Up 14 hours    5557/tcp, 0.0.0.0:8089->8089/tcp, :::8089->8089/tcp
pdfsvc_locust_1
2b1c77166423   library_api_backend    "/bin/sh -c 'bash -c…"   15 hours ago
  Up 2 minutes   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp
library_api_backend_1
a9a3140949cc   postgres:13.3-alpine   "docker-entrypoint.s…"   15 hours ago
  Up 2 minutes   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp
library_api_db_1
(env) ***@***.***:~/srik/library_api$

AND
 docker logs library_api_backend_1 is showing some errors below

(Background on this error at: https://sqlalche.me/e/14/e3q8)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5205f7ee4785, First
migration
INFO:     Will watch for changes in these directories: ['/code']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [8] using watchgod
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in
_bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in
run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line
76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68,
in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 76,
in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line
448, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in
_call_with_frames_removed
  File "/code/./app/main.py", line 5, in <module>
    from app.api import books, users
  File "/code/./app/api/books.py", line 3, in <module>
    from app.api.users import get_current_user
  File "/code/./app/api/users.py", line 7, in <module>
    from werkzeug.security import check_password_hash
ModuleNotFoundError: No module named 'werkzeug'
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO:     Will watch for changes in these directories: ['/code']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [8] using watchgod
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in
_bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in
run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line
76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68,
in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 76,
in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line
448, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in
_call_with_frames_removed
  File "/code/./app/main.py", line 5, in <module>
    from app.api import books, users
  File "/code/./app/api/books.py", line 3, in <module>
    from app.api.users import get_current_user
  File "/code/./app/api/users.py", line 7, in <module>
    from werkzeug.security import check_password_hash
ModuleNotFoundError: No module named 'werkzeug'
(env) ***@***.***:~/srik/library_api$ clear
(env) ***@***.***:~/srik/library_api$ docker logs
library_api_backend_1
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py",
line 3212, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 425, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py",
line 256, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 368, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File
"/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py",
line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py",
line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 605, in __connect
    connection = pool._invoke_creator(self)
  File
"/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line
578, in connect
    return dialect.connect(*cargs, **cparams)
  File
"/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line
584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line
122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
Is the server running on host "db" (172.23.0.2) and accepting
TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line
559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line
553, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line
530, in run_cmd
    fn(
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line
294, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py",
line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py",
line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/compat.py",
line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in
_call_with_frames_removed
  File "alembic/env.py", line 81, in <module>
    run_migrations_online()
  File "alembic/env.py", line 69, in run_migrations_online
    with connectable.connect() as connection:
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py",
line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py",
line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py",
line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py",
line 3215, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py",
line 2069, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py",
line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py",
line 3212, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 425, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py",
line 256, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 368, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File
"/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py",
line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py",
line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py",
line 605, in __connect
    connection = pool._invoke_creator(self)
  File
"/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line
578, in connect
    return dialect.connect(*cargs, **cparams)
  File
"/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line
584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line
122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not
connect to server: Connection refused
Is the server running on host "db" (172.23.0.2) and accepting
TCP/IP connections on port 5432?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5205f7ee4785, First
migration
INFO:     Will watch for changes in these directories: ['/code']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [8] using watchgod
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in
_bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in
run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line
76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68,
in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 76,
in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line
448, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in
_call_with_frames_removed
  File "/code/./app/main.py", line 5, in <module>
    from app.api import books, users
  File "/code/./app/api/books.py", line 3, in <module>
    from app.api.users import get_current_user
  File "/code/./app/api/users.py", line 7, in <module>
    from werkzeug.security import check_password_hash
ModuleNotFoundError: No module named 'werkzeug'
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO:     Will watch for changes in these directories: ['/code']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [8] using watchgod
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in
_bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in
run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/subprocess.py", line
76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68,
in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 76,
in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line
448, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line
21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in
_call_with_frames_removed
  File "/code/./app/main.py", line 5, in <module>
    from app.api import books, users
  File "/code/./app/api/books.py", line 3, in <module>
    from app.api.users import get_current_user
  File "/code/./app/api/users.py", line 7, in <module>
    from werkzeug.security import check_password_hash
ModuleNotFoundError: No module named 'werkzeug'
(env) ***@***.***:~/srik/library_api$

Please guide in your free time.

Thanks
srikanth

**Comment by luisgc93** [comment] 2022-01-24 15:15
Thanks for reporting. I've reproduced the issue on a linux (ubuntu) machine. I thought fastapi was installing werkzeug (worked on my mac) but somehow this wasn't the case on linux. I've added this to the requirements.txt file:

https://github.com/luisgc93/library_api/commit/ffd5c12e56f23fdd4a8963197c2897dd0c251465

Try pulling the new changes and then running:

```
make recreate
```

Let me know how it goes.

*Just for the record, there's no need to submit the whole stack trace, the last part would have been enoguh

**Comment by pvssrikanth** [comment] 2022-01-25 05:26
Sure Sir,
I will again git clone

and execute make recreate and run and will let you know

Thanks for your guidance.

Regards,

**Comment by pvssrikanth** [comment] 2022-01-25 09:26
Respected Sir,
Very excited to see Docker images running now library_api. *Thanks a lot *

[image: image.png]

I want to use this GREAT API and customize for my projects.

Thanking you

But i just want documentation , how to use because if created one user and
clicked authorize but

[image: image.png]

Is there any documentation how to use the flow like
create users
login
POST , GET Libray APIs etc.

Thanks again
srikanth

**Comment by luisgc93** [comment] 2022-01-25 15:33
Hi @pvssrikanth, I'm glad it worked. The images you attached are not showing up so I'm not sure what the issue is. I've updated the project readme with a usage section:

https://github.com/luisgc93/library_api

The docs are also deployed at:
http://book-api-fastapi-project.herokuapp.com/docs

If that's ok then I'll close this issue. Feel free to star this project if you've find it useful. Let me know if there's any further questions.

**Comment by pvssrikanth** [comment] 2022-01-26 13:40
Dear Sir,
This project is very useful.

But i am unable to get authentication successful.

***@***.***:~/srik$ curl --location --request POST '
192.168.0.238:8000/login/' --header 'Content-Type: application/json'
--data-raw '{    "username": "siva",

    "password": ***@***.***"
}'
***@***.***:~/srik$

***@***.***:~/srik$
***@***.***:~/srik$ curl --location --request POST '
192.168.0.238:8000/books/' \
> --header 'Authorization:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzaXZhIiwiZXhwIjoxNjQzMjA3Nzg4fQ.aZpLuh1s8pf0oSxEXDApqT9AxSonCbaftKwtiaLTRVg'
\
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "title": "Harry Potter and the Philosopher'\''s Stone",
>     "author": "J. K. Rowling"
> }'
{"detail":"Not ***@***.***:~/srik$

**Comment by luisgc93** [comment] 2022-01-26 16:34
You should use instead:

```
curl --location --request POST '0.0.0.0:8000/books/' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzaXZhIiwiZXhwIjoxNjQzMjA3Nzg4fQ.aZpLuh1s8pf0oSxEXDApqT9AxSonCbaftKwtiaLTRVg' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Harry Potter and the Philosopher'\''s Stone",
    "author": "J. K. Rowling"
}'

**Comment by pvssrikanth** [comment] 2022-01-27 05:27
Dear Sir,
I am getting Internal Error This time.

*Internal Server ***@***.***:~$ *

Could you please correct where i am typing wrong command

curl --location --request POST '192.168.0.238:8000/users/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "kalyan",
    "password": ***@***.***"
}'

curl --location --request POST '192.168.0.238:8000/login/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "kalyan",
    "password": ***@***.***"
}'



curl --location --request POST '192.168.0.238:8000/books/' \
--header 'Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYWx5YW4iLCJleHAiOjE2NDMyNjQ1Mzh9.fZkiOVPpUN2rixPIVEGL5XNBnd4kHRgMSbKoh_queMo'
\
--header 'Content-Type: application/json' \
--data-raw '{
      "title": "pran ",
    "author": "kalyan"
}'

Thanks for your support.

**Comment by luisgc93** [comment] 2022-01-28 14:41
I don't know what the error is because you didn't share the error output. I suggest you use an http client tool like Postman:
https://www.postman.com/downloads/

I've used postman and obtained the cURL commands from there. These are the commands:

Create a user:
```
curl --location --request POST '0.0.0.0:8000/users/' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZXRhLXVzZXIiLCJleHAiOjE2NDI5NzQ4MjR9.P-HdAJmr3TywpdFwz2CiO5pfapD8tBPamdwTEbsAVOo' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "user",
    "password": "password"
}
'
```
Login with the user credentials:

```
curl --location --request POST '0.0.0.0:8000/login/' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZXRhLXVzZXIiLCJleHAiOjE2NDI5NzQ4MjR9.P-HdAJmr3TywpdFwz2CiO5pfapD8tBPamdwTEbsAVOo' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "user",
    "password": "password"
}
'
```
Create a book with POST books using the auth header:

```
curl --location --request POST '0.0.0.0:8000/books/' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZXRhLXVzZXIiLCJleHAiOjE2NDI5NzQ4MjR9.P-HdAJmr3TywpdFwz2CiO5pfapD8tBPamdwTEbsAVOo' \
--header 'Content-Type: application/json' \
--data-raw '{
    "title": "Harry Potter and the Philosopher'\''s Stone",
    "author": "J. K. Rowling"
}'
```

**Closed by luisgc93** 2022-01-28 14:41 UTC

**Comment by luisgc93** [comment] 2022-01-28 14:44
If you get an internal server error you need to check the backend container logs. My guess is that there already exists a user under that name. The api doesn't currently handle this.

**Comment by pvssrikanth** [comment] 2022-01-28 14:59
Ok Sir

I will try to understand

But public API doesn't have authorisation
